/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_login_LoginActivity */

#ifndef _Included_cn_itcast_login_LoginActivity
#define _Included_cn_itcast_login_LoginActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_login_LoginActivity
 * Method:    call_login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_itcast_login_LoginActivity_call_1login
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
