/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_lame_LameActivity */

#ifndef _Included_cn_itcast_lame_LameActivity
#define _Included_cn_itcast_lame_LameActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_lame_LameActivity
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_itcast_lame_LameActivity_convertmp3
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_itcast_lame_LameActivity
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_itcast_lame_LameActivity_getLameVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
