/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_monitor_DemoActivity */

#ifndef _Included_cn_itcast_monitor_DemoActivity
#define _Included_cn_itcast_monitor_DemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_monitor_DemoActivity
 * Method:    getPressure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_itcast_monitor_DemoActivity_getPressure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
