/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_ndk_HelloWorld */

#ifndef _Included_cn_itcast_ndk_HelloWorld
#define _Included_cn_itcast_ndk_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_ndk_HelloWorld
 * Method:    hellofromc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_itcast_ndk_HelloWorld_hellofromc
  (JNIEnv *, jobject);

/*
 * Class:     cn_itcast_ndk_HelloWorld
 * Method:    hello_from_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_itcast_ndk_HelloWorld_hello_1from_1c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
