/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_ndk_DemoActivity */

#ifndef _Included_cn_itcast_ndk_DemoActivity
#define _Included_cn_itcast_ndk_DemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_ndk_DemoActivity
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_itcast_ndk_DemoActivity_helloFromC
  (JNIEnv *, jobject);

/*
 * Class:     cn_itcast_ndk_DemoActivity
 * Method:    hello_from_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_itcast_ndk_DemoActivity_hello_1from_1c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
