/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_ndkcallback_DemoActivity */

#ifndef _Included_cn_itcast_ndkcallback_DemoActivity
#define _Included_cn_itcast_ndkcallback_DemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_ndkcallback_DemoActivity
 * Method:    call_dp_method1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_itcast_ndkcallback_DemoActivity_call_1dp_1method1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
